import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontFamily: "Helvetica",
    fontSize: 11,
    color: "#0f172a",
    lineHeight: 1.5,
  },
  brand: {
    fontSize: 10,
    color: "#345ff2",
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 6,
  },
  title: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  subtitle: { fontSize: 11, color: "#475569", marginBottom: 24 },
  scoreBox: {
    backgroundColor: "#eef4ff",
    borderRadius: 8,
    padding: 16,
    marginBottom: 24,
  },
  scorePercent: {
    fontSize: 32,
    fontFamily: "Helvetica-Bold",
    color: "#2036aa",
  },
  scoreSub: { fontSize: 10, color: "#475569" },
  outcomeTitle: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    marginTop: 24,
    marginBottom: 6,
    color: "#1f3087",
  },
  outcomeBody: { marginBottom: 18 },
  sectionHeading: {
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 1.5,
    color: "#475569",
    marginBottom: 8,
    marginTop: 18,
  },
  infoRow: { flexDirection: "row", marginBottom: 3 },
  infoLabel: { width: 80, color: "#64748b" },
  infoValue: { flex: 1, fontFamily: "Helvetica-Bold" },
  answerBlock: { marginBottom: 12 },
  answerQ: { fontFamily: "Helvetica-Bold", marginBottom: 2 },
  answerA: { color: "#334155" },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 48,
    right: 48,
    textAlign: "center",
    fontSize: 9,
    color: "#94a3b8",
  },
});

export type PdfData = {
  quizTitle: string;
  ownerName: string | null;
  respondent: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    company: string;
    jobTitle: string;
  };
  scorePercent: number;
  score: number;
  maxScore: number;
  outcomeTitle?: string;
  outcomeDescription?: string;
  answers: {
    question: string;
    answer: string;
  }[];
  completedAt: Date;
};

function ReportDocument({ data }: { data: PdfData }) {
  const r = data.respondent;
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>Flowscore report</Text>
        <Text style={styles.title}>{data.quizTitle}</Text>
        <Text style={styles.subtitle}>
          {r.firstName} {r.lastName} · {data.completedAt.toLocaleDateString()}
        </Text>

        <View style={styles.scoreBox}>
          <Text style={styles.scorePercent}>{data.scorePercent.toFixed(1)}%</Text>
          <Text style={styles.scoreSub}>
            {data.score.toFixed(1)} of {data.maxScore.toFixed(1)} points
          </Text>
        </View>

        {data.outcomeTitle && (
          <View>
            <Text style={styles.sectionHeading}>Your outcome</Text>
            <Text style={styles.outcomeTitle}>{data.outcomeTitle}</Text>
            {data.outcomeDescription && (
              <Text style={styles.outcomeBody}>{data.outcomeDescription}</Text>
            )}
          </View>
        )}

        <Text style={styles.sectionHeading}>Your details</Text>
        <InfoRow label="Name" value={`${r.firstName} ${r.lastName}`.trim()} />
        <InfoRow label="Email" value={r.email} />
        {r.phone && <InfoRow label="Phone" value={r.phone} />}
        {r.company && <InfoRow label="Company" value={r.company} />}
        {r.jobTitle && <InfoRow label="Role" value={r.jobTitle} />}

        <Text style={styles.sectionHeading}>Your answers</Text>
        {data.answers.map((a, i) => (
          <View key={i} style={styles.answerBlock}>
            <Text style={styles.answerQ}>
              {i + 1}. {a.question}
            </Text>
            <Text style={styles.answerA}>{a.answer || "—"}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Report generated by Flowscore
          {data.ownerName ? ` for ${data.ownerName}` : ""}.
        </Text>
      </Page>
    </Document>
  );
}

function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.infoRow}>
      <Text style={styles.infoLabel}>{label}</Text>
      <Text style={styles.infoValue}>{value}</Text>
    </View>
  );
}

export async function generatePdfBuffer(data: PdfData): Promise<Buffer> {
  return renderToBuffer(<ReportDocument data={data} />);
}
